### ISSUE TITLE
Auto update invoicing in new billing item

### ISSUE THREAD

**Issue by mycatsname1** [haakonsmith/xqflite#5]
When creating a new billing item there's an issue where it unselects the text field you're editing. I'm guessing this is because of the preview invoice that gets updated after information has been changed. idk how it works but I'm guessing the fix would be to only update the preview invoice after like 10 seconds of text being added or remove the thing where it unselects the text field you're editing. 

![Image](https://github.com/user-attachments/assets/231cb321-2eaa-42aa-9beb-398ee038cdd5)

**Comment by haakonsmith** [comment]
Awesome, thanks for creating an issue! In the future can you please not click the convert to issue button?
